<?php


namespace Bitapp\CoreApi\Command;


use Bitapp\CoreApi\Router\Request\RequestContext;

class Command extends CommandBase
{

    public function exec(RequestContext $context)
    {
        parent::exec($context); // TODO: Change the autogenerated stub
    }
}